# -*- coding: utf-8 -*-
"""크롤크

generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-SvI7sdp7_luREWJrB2yfLniFo0EifH6
"""

# Windows 환경에서 필요한 패키지 설치
# 터미널에서 다음 명령어를 실행하세요:
# pip install selenium beautifulsoup4 requests pandas pypdf lxml webdriver-manager

import subprocess
import sys

def install_packages():
    """필요한 패키지들을 자동으로 설치합니다."""
    packages = ['selenium', 'beautifulsoup4', 'requests', 'pandas', 'pypdf', 'lxml', 'webdriver-manager']
    for package in packages:
        try:
            __import__(package.replace('-', '_'))
        except ImportError:
            print(f"패키지 '{package}' 설치 중...")
            subprocess.check_call([sys.executable, '-m', 'pip', 'install', package])
            print(f"'{package}' 설치 완료!")

# 패키지 자동 설치 (필요시 주석 해제)
# install_packages()

import sys
import os
import re
import time
import math
import json
import glob
import base64
import requests
import pandas as pd

from dataclasses import dataclass
from collections import deque
from typing import List, Dict, Any, Optional
from urllib.parse import urljoin, urlparse
from urllib.robotparser import RobotFileParser
from pypdf import PdfReader
from bs4 import BeautifulSoup

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager

BASE_URL="https://www.hanyang.ac.kr"
PORTAL_BASE_URL = "https://portal.hanyang.ac.kr"
COURSE_LIST_PATH = "/sugang/SgscAct/findSuupSearchSugangSiganpyo.do"


"""
# HyuCoursesCrawler

# HyuSyllabusCrawler

# HyuPagesCrawler
"""

@dataclass
class SeedPage:
    category: str
    title: str
    url: str

SEED_PAGES = [
    SeedPage("서울캠퍼스/캠퍼스 소개", "서울캠퍼스는", "https://www.hanyang.ac.kr/web/www/seoul"),
    SeedPage("서울캠퍼스/캠퍼스 소개", "대학, 학과 소개", "https://www.hanyang.ac.kr/web/www/s_college_department-info"),
    SeedPage("서울캠퍼스/캠퍼스 소개", "대학원", "https://www.hanyang.ac.kr/web/www/grad"),
    SeedPage("서울캠퍼스/학사 안내", "학사일정", "https://www.hanyang.ac.kr/web/www/-33"),
    SeedPage("서울캠퍼스/학사 안내", "수강신청", "https://www.hanyang.ac.kr/web/www/-48"),
    SeedPage("서울캠퍼스/학사 안내", "수업 안내", "https://www.hanyang.ac.kr/web/www/-50"),
    SeedPage("서울캠퍼스/학사 안내", "온라인 강좌", "https://www.hanyang.ac.kr/web/www/-51"),
    SeedPage("서울캠퍼스/학사 안내", "학적변동", "https://www.hanyang.ac.kr/web/www/-53"),
    SeedPage("서울캠퍼스/학사 안내", "성적, 졸업", "https://www.hanyang.ac.kr/web/www/75"),
    SeedPage("서울캠퍼스/학사 안내", "학점인정", "https://www.hanyang.ac.kr/web/www/-54"),
    SeedPage("서울캠퍼스/행정 지원 안내", "업무별 담당 부서 안내", "https://www.hanyang.ac.kr/web/www/-73"),
    SeedPage("서울캠퍼스/행정 지원 안내", "등록 안내", "https://www.hanyang.ac.kr/web/www/s_registration-guide"),
    SeedPage("서울캠퍼스/행정 지원 안내", "장학 안내", "https://www.hanyang.ac.kr/web/www/sc_s"),
    SeedPage("서울캠퍼스/행정 지원 안내", "기숙사 안내", "https://www.hanyang.ac.kr/web/www/dormitory"),
    SeedPage("서울캠퍼스/행정 지원 안내", "증명발급 안내", "https://www.hanyang.ac.kr/web/www/diploma_seoul"),
    SeedPage("서울캠퍼스/행정 지원 안내", "학생대관", "https://www.hanyang.ac.kr/web/www/rent_s1"),
    SeedPage("서울캠퍼스/기관, 단체", "행정기관", "https://www.hanyang.ac.kr/web/www/-101"),
    SeedPage("서울캠퍼스/기관, 단체", "부속, 부설기관", "https://www.hanyang.ac.kr/web/www/-103"),
    SeedPage("서울캠퍼스/기관, 단체", "학생 기구", "https://www.hanyang.ac.kr/web/www/student_s"),
    SeedPage("서울캠퍼스/기관, 단체", "동아리 안내", "https://www.hanyang.ac.kr/web/www/club_s"),
    SeedPage("서울캠퍼스/기관, 단체", "학생 언론사", "https://www.hanyang.ac.kr/web/www/-41"),
    SeedPage("서울캠퍼스/대학 생활", "IT 서비스", "https://www.hanyang.ac.kr/web/www/it_s"),
    SeedPage("서울캠퍼스/대학 생활", "복지 매장", "https://www.hanyang.ac.kr/web/www/facilities_s"),
    SeedPage("서울캠퍼스/대학 생활", "복지 혜택", "https://www.hanyang.ac.kr/web/www/benefit_s"),
    SeedPage("서울캠퍼스/대학 생활", "보건 안내", "https://www.hanyang.ac.kr/web/www/health_s"),
    SeedPage("서울캠퍼스/대학 생활", "의료혜택", "https://www.hanyang.ac.kr/web/www/medicalcare_s"),
    SeedPage("서울캠퍼스/대학 생활", "학생 상담", "https://www.hanyang.ac.kr/web/www/counsel_s"),
    SeedPage("서울캠퍼스/대학 생활", "인권센터", "https://www.hanyang.ac.kr/web/www/gender_s"),
    SeedPage("서울캠퍼스/대학 생활", "병무안내", "https://www.hanyang.ac.kr/web/www/military_s"),
    SeedPage("서울캠퍼스/대학 생활", "고시반 안내", "https://www.hanyang.ac.kr/web/www/exam_s"),
    SeedPage("입학, 교육/입학총괄", "대학, 대학원 전체 입체안내", "https://www.hanyang.ac.kr/web/www/admissions-guide"),
    SeedPage("입학, 교육", "학술 정보", "https://www.hanyang.ac.kr/web/www/library"),
    SeedPage("입학, 교육/글로벌 교육", "국제교류(서울)", "https://www.hanyang.ac.kr/web/www/global_s"),
    SeedPage("입학, 교육/사회봉사", "사랑의 실천", "https://www.hanyang.ac.kr/web/www/love_indeed"),
 
    SeedPage("서울캠퍼스/대학 생활", "병무안내", "https://www.hanyang.ac.kr/web/www/military_s"),
    SeedPage("서울캠퍼스/대학 생활", "고시반 안내", "https://www.hanyang.ac.kr/web/www/exam_s"),
    SeedPage("입학, 교육/입학총괄", "대학, 대학원 전체 입체안내", "https://www.hanyang.ac.kr/web/www/admissions-guide"),
    SeedPage("입학, 교육", "학술 정보", "https://www.hanyang.ac.kr/web/www/library"),
    SeedPage("입학, 교육/글로벌 교육", "국제교류(서울)", "https://www.hanyang.ac.kr/web/www/global_s"),
    SeedPage("입학, 교육/사회봉사", "사랑의 실천", "https://www.hanyang.ac.kr/web/www/love_indeed"),
    
    # 한양대학교 서울 학사안내 도메인 추가
    SeedPage("학사안내/학적", "학적변동 신청, 문의", "https://academic.hanyang.ac.kr/%ED%95%99%EC%A0%81%EB%B3%80%EB%8F%99-%EC%8B%A0%EC%B2%AD"),
    SeedPage("학사안내/학적", "학적사항 정정/학적부 정정", "https://academic.hanyang.ac.kr/8_"),
    SeedPage("학사안내/학적", "학적사항 정정/신상정보 정정", "https://academic.hanyang.ac.kr/-30"),
    SeedPage("학사안내/학적", "휴학", "https://academic.hanyang.ac.kr/%ED%9C%B4%ED%95%99"),
    SeedPage("학사안내/학적", "복학", "https://academic.hanyang.ac.kr/%EB%B3%B5%ED%95%99"),
    SeedPage("학사안내/학적", "자진유급", "https://academic.hanyang.ac.kr/%EC%9E%90%EC%A7%84%EC%9C%A0%EA%B8%89"),
    SeedPage("학사안내/학적", "자퇴, 제적", "https://academic.hanyang.ac.kr/9_"),
    SeedPage("학사안내/학적", "재입학 안내", "https://academic.hanyang.ac.kr/60-1"),
    SeedPage("학사안내/학적", "재입학운영내규", "https://academic.hanyang.ac.kr/-70"),
    SeedPage("학사안내/학적", "전과", "https://academic.hanyang.ac.kr/-69"),
    SeedPage("학사안내/학적", "FAQ", "https://academic.hanyang.ac.kr/faq"),
    
    SeedPage("학사안내/전공", "부전공", "https://academic.hanyang.ac.kr/-9"),
    SeedPage("학사안내/전공", "다중, 융합전공", "https://academic.hanyang.ac.kr/-10"),
    SeedPage("학사안내/전공", "복수전공", "https://academic.hanyang.ac.kr/-12"),
    SeedPage("학사안내/전공/마이크로전공", "공과대학", "https://academic.hanyang.ac.kr/-60"),
    SeedPage("학사안내/전공/마이크로전공", "인문과학대학", "https://academic.hanyang.ac.kr/-72"),
    SeedPage("학사안내/전공/마이크로전공", "사회과학대학", "https://academic.hanyang.ac.kr/-73"),
    SeedPage("학사안내/전공/마이크로전공", "경제금융대학", "https://academic.hanyang.ac.kr/-74"),
    SeedPage("학사안내/전공/마이크로전공", "경영대학", "https://academic.hanyang.ac.kr/-75"),
    SeedPage("학사안내/전공/마이크로전공", "생활과학대학", "https://academic.hanyang.ac.kr/-76"),
    SeedPage("학사안내/전공/마이크로전공", "자연과학대학", "https://academic.hanyang.ac.kr/-80"),
    SeedPage("학사안내/전공/마이크로전공", "국제대학", "https://academic.hanyang.ac.kr/%EA%B5%AD%EC%A0%9C%EB%8C%80%ED%95%99"),
    SeedPage("학사안내/전공/마이크로전공", "융합전공대학", "https://academic.hanyang.ac.kr/-77"),
    SeedPage("학사안내/전공/마이크로전공", "미래인문학교육인증센터", "https://academic.hanyang.ac.kr/-82"),
    
    SeedPage("학사안내/교육과정/2024-2027", "비전 및 목표", "https://academic.hanyang.ac.kr/%EB%B9%84%EC%A0%84-%EB%B0%8F-%EB%AA%A9%ED%91%9C2"),
    SeedPage("학사안내/교육과정/2024-2027", "이수단위 정의", "https://academic.hanyang.ac.kr/%EC%9D%B4%EC%88%98%EB%8B%A8%EC%9C%84-%EC%A0%95%EC%9D%981"),
    SeedPage("학사안내/교육과정/2024-2027", "주전공 이수 조건", "https://academic.hanyang.ac.kr/%EC%A3%BC%EC%A0%84%EA%B3%B5-%EC%9D%B4%EC%88%98-%EC%A1%B0%EA%B1%B41"),
    SeedPage("학사안내/교육과정/2024-2027", "리더십 인증 로드맵", "https://academic.hanyang.ac.kr/%EB%A6%AC%EB%8D%94%EC%8B%AD-%EC%9D%B8%EC%A6%9D-%EB%A1%9C%EB%93%9C%EB%A7%B54"),
    
    SeedPage("학사안내/교육과정/2020-2023", "비전 및 목표", "https://academic.hanyang.ac.kr/2020-2023-1"),
    SeedPage("학사안내/교육과정/2020-2023", "이수단위 정의", "https://academic.hanyang.ac.kr/2020-2023-2"),
    SeedPage("학사안내/교육과정/2020-2023", "주전공 이수 조건", "https://academic.hanyang.ac.kr/2020-2023-3"),
    SeedPage("학사안내/교육과정/2020-2023", "리더십 인증 로드맵", "https://academic.hanyang.ac.kr/2020-2023-4"),
    
    SeedPage("학사안내/수업/정규학기", "온라인강좌안내", "https://academic.hanyang.ac.kr/-17"),
    SeedPage("학사안내/수업/정규학기", "특수수업", "https://academic.hanyang.ac.kr/-18"),
    SeedPage("학사안내/수업/정규학기", "스마트출결시스템", "https://academic.hanyang.ac.kr/-19"),
    SeedPage("학사안내/수업/정규학기", "강의평가", "https://academic.hanyang.ac.kr/-20"),
    SeedPage("학사안내/수업/정규학기", "수업도우미", "https://academic.hanyang.ac.kr/-32"),
    
    SeedPage("학사안내/수업/계절학기", "계절학기 안내", "https://academic.hanyang.ac.kr/-36"),
    SeedPage("학사안내/수업/계절학기", "계절학기 수요조사", "https://academic.hanyang.ac.kr/-58"),
    SeedPage("학사안내/수업/계절학기", "부분환불원칙", "https://academic.hanyang.ac.kr/-62"),
    
    SeedPage("학사안내/수업", "본교생 학점교류(out)", "https://academic.hanyang.ac.kr/-15"),
    SeedPage("학사안내/수업", "강의동 및 행정팀안내", "https://academic.hanyang.ac.kr/-38"),
    
    SeedPage("학사안내/성적", "성적", "https://academic.hanyang.ac.kr/-22"),
    SeedPage("학사안내/성적", "학점포기", "https://academic.hanyang.ac.kr/-23"),
    SeedPage("학사안내/성적", "외국대학취득학점인정", "https://academic.hanyang.ac.kr/-39"),
    SeedPage("학사안내/성적", "인턴십", "https://academic.hanyang.ac.kr/-40"),
    
    SeedPage("학사안내/졸업", "졸업요건", "https://academic.hanyang.ac.kr/-24"),
    SeedPage("학사안내/졸업", "조기졸업", "https://academic.hanyang.ac.kr/-25"),
    SeedPage("학사안내/졸업", "학사학위취득유예", "https://academic.hanyang.ac.kr/-26"),
    
    SeedPage("학사안내/증명", "증명발급 안내", "https://academic.hanyang.ac.kr/%EC%A6%9D%EB%AA%85%EB%B0%9C%EA%B8%89%EC%95%88%EB%82%B4"),
    SeedPage("학사안내/증명/증명발급 방법", "인터넷증명발급(HY-in)", "https://academic.hanyang.ac.kr/%EC%9D%B8%ED%84%B0%EB%84%B7%EC%A6%9D%EB%AA%85%EB%B0%9C%EA%B8%89"),
    SeedPage("학사안내/증명/증명발급 방법", "FAX민원(정부24)", "https://academic.hanyang.ac.kr/fax%EB%AF%BC%EC%9B%90"),
    SeedPage("학사안내/증명/증명발급 방법", "우편증명발급", "https://academic.hanyang.ac.kr/%EC%9A%B0%ED%8E%B8%EC%A6%9D%EB%AA%85%EB%B0%9C%EA%B8%89"),
    SeedPage("학사안내/증명/증명발급 방법", "학교 방문발급", "https://academic.hanyang.ac.kr/%EB%B0%A9%EB%AC%B8%EB%B0%9C%EA%B8%89"),
    SeedPage("학사안내/증명", "원본대조확인", "https://academic.hanyang.ac.kr/%EC%9B%90%EB%B3%B8%EB%8C%80%EC%A1%B0%ED%99%95%EC%9D%B8"),
]

PAGE_DIR = "./hyu_pages"
os.makedirs(PAGE_DIR, exist_ok=True)

BASE_DIR = PAGE_DIR # BASE_DIR 정의 추가

# requests Session 생성
session = requests.Session()

def safe_name(s: str) -> str:
    s = re.sub(r"[^\w가-힣\-]+", "_", s)
    return s[:80]

def extract_main_text(html: str) -> str:
    soup = BeautifulSoup(html, "lxml")

    # 1차: 자주 쓰이는 컨텐츠 영역 id/class 추측
    candidates = []
    for selector in [
        "div#content",
        "div#contents",
        "div.article",
        "div.article-wrap",
        "div.hyu_cont",
        "div.hyu_cont_wrap",
        "main",
        "article",
    ]:
        cand = soup.select_one(selector)
        if cand:
            candidates.append(cand)

    if candidates:
        best = max(candidates, key=lambda c: len(c.get_text(strip=True)))
        text = best.get_text("\n", strip=True)
    else:
        # fallback: body 전체
        body = soup.body or soup
        text = body.get_text("\n", strip=True)

    # 공백 정리
    lines = [line.strip() for line in text.splitlines()]
    lines = [line for line in lines if line]
    return "\n".join(lines)

def download_pdfs(html: str, page_url: str, out_dir: str):
    soup = BeautifulSoup(html, "lxml")
    pdf_links = []
    for a in soup.find_all("a", href=True):
        href = a["href"]
        if ".pdf" in href.lower():
            pdf_links.append(urljoin(page_url, href))

    pdf_links = list(dict.fromkeys(pdf_links))  # 중복 제거

    pdf_dir = os.path.join(out_dir, "pdf")
    if pdf_links:
        os.makedirs(pdf_dir, exist_ok=True)

    for i, pdf_url in enumerate(pdf_links, start=1):
        try:
            r = session.get(pdf_url, timeout=15)
            r.raise_for_status()
        except Exception as e:
            print(f"[PDF FAIL] {pdf_url} -> {e}")
            continue

        fname = os.path.join(pdf_dir, f"doc_{i:02d}.pdf")
        with open(fname, "wb") as f:
            f.write(r.content)
        print(f"[PDF] saved {fname}")

def crawl_seed_page(seed: SeedPage):
    folder_name = safe_name(f"{seed.category}_{seed.title}")
    out_dir = os.path.join(BASE_DIR, folder_name)
    
    # 이미 크롤링된 페이지인지 확인
    meta_path = os.path.join(out_dir, "meta.json")
    html_path = os.path.join(out_dir, "page.html")
    
    if os.path.exists(meta_path) and os.path.exists(html_path):
        print(f"\n[SKIP] {seed.title} ({seed.url}) - 이미 크롤링됨")
        return

    print(f"\n[REQ] {seed.title} ({seed.url})")

    driver = None
    try:
        chrome_options = Options()
        chrome_options.add_argument('--headless')
        chrome_options.add_argument('--no-sandbox')
        chrome_options.add_argument('--disable-dev-shm-usage')
        chrome_options.add_argument('user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36')
        # Windows에서 ChromeDriver 자동 관리
        service = Service(ChromeDriverManager().install())
        driver = webdriver.Chrome(service=service, options=chrome_options)

        driver.get(seed.url)
        # 페이지 로딩 대기 (필요에 따라 명시적 대기 조건 추가 가능)
        time.sleep(3) # 3초 대기, 동적 콘텐츠 로딩을 위해 충분한 시간을 줍니다.
        html = driver.page_source

    except Exception as e:
        print(f"[ERROR] request failed: {e}")
        return
    finally:
        if driver:
            driver.quit()

    os.makedirs(out_dir, exist_ok=True)

    # 1) raw html 저장
    html_path = os.path.join(out_dir, "page.html")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"[SAVE] HTML -> {html_path}")

    # 2) 본문 텍스트 추출
    text = extract_main_text(html)
    txt_path = os.path.join(out_dir, "content.txt")
    with open(txt_path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"[SAVE] TEXT -> {txt_path}, length={len(text)}")

    # 3) 메타데이터 저장
    meta = {
        "category": seed.category,
        "title": seed.title,
        "url": seed.url,
        "html_path": html_path,
        "text_path": txt_path,
    }
    meta_path = os.path.join(out_dir, "meta.json")
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(meta, f, ensure_ascii=False, indent=2)
    print(f"[SAVE] META -> {meta_path}")

    # 4) pdf 링크 있으면 저장
    download_pdfs(html, seed.url, out_dir)


for seed in SEED_PAGES:
    crawl_seed_page(seed)
    time.sleep(0.5)  # 너무 빠른 연속요청 방지